---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kafka.confluent.crossplane.io
  resources:
  - topic
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - v1
  resources:
  - secret
  verbs:
  - get
  - list
  - watch
